# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'iHouse' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iHouse
  pod 'RNMobileCenter', '~> 0.1.0'
  pod 'MobileCenter', '~> 0.3.0'

  

end
